title: Shadow Client Docs
description: Shadow Client documentation.
theme: just-the-docs

url: https://shadowclienthelp.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
